[WIP] MOD: features for front-side
team-tissis/polylemma pull request #125
Opened 2022-11-17 09:35 UTC by shiinokinoki

2022-11-17 16:51 UTC, terapoon requested changes
お疲れ様！！非常に助かります。
さーと読んで思ったことを雑に書き殴ってみました。
できる範囲で修正して、一旦 pending する部分はソースコードにその旨を TODO などでコメントを残してリファクタしやすいようにしてもらえるとです。

getter しか書いてないけど、storage の追加とか色々あるので、少なくとも今書いてあるテストには通ることは一度確認をお願いします。

```
forge build
forge test
```

明日は稼働取れるか怪しいので、ノキノキが今やるべきと感じた部分で修正を入れてもらってマージしてもらって大丈夫です。approve 押すくらいなら何とかなるかと。

あまり大きな変更を行うとむしろ追えなくなるので、逆に変更はあまりせず、変更が必要 or 変更の可能性がある箇所にコメントを残しておく部分をお願いしたいです。

@terapoon は土曜に引き継いでリファクタを一旦ガーっとやろうと思っています。

明日はこれのマージが終わったら例の知見まとめ or polylemma 以外のタスクで大丈夫そうです。
暇だったらリファクタのアイディアとかをコード中 or 何処かにさーと書き出しておいてくれると、その内容も反映して作業したいと思います。

2022-11-17 16:51 UTC, terapoon commented on src/interfaces/IPLMBattleField.sol
> +        uint8[5] slotsUsed;
why bool -> uint8 ??

2022-11-17 16:51 UTC, terapoon commented on src/interfaces/IPLMBattleField.sol
> +    enum PlayerStateFromFrontSide {
これ、流石に冗長じゃない？
ここまでやる必要ないのではと感じる...

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +                _getSlotUsedFlag(playerId, uint8(choice)) != 0)
getFixedSlotUsedFlag を getSlotUsedFlag に統一するという変更をしたのに475行目では結局ランダムスロットに対しては getRandomSlotUsedFlag で取ってるから中途半端な気がする。

複数の関数で同じ役割を持つのはややこしくなるから元のままに一旦しておくか、もう fixedSlot と randomSlot を同一視するような形にするかのどちらかにはっきりするべきだと感じる。

(現状明確に分けた実装になってるので、この getter を追加するタイミングでこの中途半端なリファクタをするのは好ましくなさそう。)

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +        // rest roundResult array
やっぱ Array シビアだな...
まあここの修正はリファクタでやるので一旦これでよし。

2022-11-17 16:51 UTC, terapoon commented on src/interfaces/IPLMBattleField.sol
> +        uint8[5] slotsUsed;
あー、使われたラウンドを記録してるってことか。下の方読んでて理解しました。

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +    function getPlayerStateFromFrontSide(PlayerId fpId)
非本質やけど、引数名の fpId って何の略や ??
これまで playerId を使ってきてたけどここであえて名前を変えてたから気になった。

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +        if (playerInfoTable[fpId].state == PlayerState.Preparing) {
この辺、_getPlayerState みたいな関数なかったっけ？
できるだけ playerInfoTable への直接のアクセスを避けたい (可読性が下がるので)

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +        if (fpId == PlayerId.Alice) {
これ、
PlayerId spId = _enemyId(fpId);
と1行で書くやつを既に用意している

あと、現状命名は基本的に playerId, enemyId に統一されている。
まあリファクタすればいいんやけども...

2022-11-17 16:51 UTC, terapoon commented on src/subcontracts/PLMBattleField.sol
> +        if (fpId == PlayerId.Alice) {
まあでも一斉置換とかしにくいし今の慣例に一旦沿っておいてもらえると色々とありがたい

2022-11-17 16:51 UTC, terapoon commented on src/interfaces/IPLMBattleField.sol
> +    enum PlayerStateFromFrontSide {
冗長では？のお気持ち
フロントに返すためだけにスマコンに enum PlayerState とほぼ同じものの拡張を拡張を置くの、無駄みを少し感じる。
めちゃめちゃ難しいロジックを組んでるならあれやが、各々の PlayerState をフロント側でサッととって解釈した方が嬉しそう。

フロントのためだけの enum をおいておくと、フロントからの要求に応じて変更が入る可能性があるし、フロントとスマコンを透過性を持たせてある程度独立なものにしたいという思想には反しているように感じた。

2022-11-17 16:51 UTC, terapoon commented on src/interfaces/IPLMBattleField.sol
> +        uint8[5] slotsUsed;
となると、変数名が不適切感ある

2022-11-18 03:45 UTC, shiinokinoki commented on src/interfaces/IPLMBattleField.sol
> +    enum PlayerStateFromFrontSide {
discordに続きを記載

2022-11-18 03:48 UTC, shiinokinoki commented on src/subcontracts/PLMBattleField.sol
> +    function getPlayerStateFromFrontSide(PlayerId fpId)
firstPersonIdですね、、、相手ありきで書きたかったからこういう書き方したけど、引数に二人取らないから、よく考えればplayerIdでいいな、、、直しておきます

2022-11-18 03:54 UTC, shiinokinoki commented
This branch passed the existing test code.

2022-11-18 04:56 UTC, shiinokinoki commented on src/subcontracts/PLMBattleField.sol
> +                _getSlotUsedFlag(playerId, uint8(choice)) != 0)
struct RandomSlotの slotUsedをroundSlotUsedに変更して、randomSlotとfixedSlotの使用ラウンドの格納場所を明確に分けて、参照する関数も分ました。

2022-11-18 05:02 UTC, shiinokinoki commented on src/subcontracts/PLMBattleField.sol
> +        if (playerInfoTable[fpId].state == PlayerState.Preparing) {
done

2022-11-18 05:03 UTC, shiinokinoki commented on src/subcontracts/PLMBattleField.sol
> +        if (fpId == PlayerId.Alice) {
修正しました

2022-11-18 05:11 UTC, shiinokinoki commented on src/interfaces/IPLMBattleField.sol
> +    enum PlayerStateFromFrontSide {
一旦TODOで置いてます

2022-11-18 05:41 UTC, terapoon approved these changes

2022-11-18 06:03 UTC, merged