[WIP] Feature/multislot battle
team-tissis/polylemma pull request #145
Opened 2023-02-25 13:26 UTC by shiinokinoki

# Description

- src/PLMBattleStorage.sol (ADD)
  - バトルに関連する情報をsstore2で write/readするコントラクト
  - sstore2で格納するにあたり，全てのデータはbytes memory の形で w/r されるので，to/from bytes の変換を行う関数．
  - sstore2でデータを格納すると返ってくるポインタを格納したmapping．readするときに使う．
  - test : test/PLMBattleStorageInternal.t.sol は，bytes への encode, decodeの関数をテストしている．
- src/PLMBattleManager.sol (ADD)
  - BattleFieldコントラクトは，BattleStorageを直接callせず，このBattleManagerの関数を call することで，データの読み書きを行う．battleIdや roundのインデックスを使って参照し，構造体などの部分的な変更など，BattleStorageを直接叩くと処理が嵩むものをラップしている．
  -  test: これそのもののテストは書いていない．BattleFieldが動くことを持ってテストとした．
- src/PLMBattleField.sol (MOD)
  - バトルの情報を格納していたmappingを全て削除．各playerがプレイしている最新のbattleIdを格納するmappingを追加．
  - バトルに関する変数は全てBattleManagerを介したBattleStorageへの書き込みに置き換えた．
  - BattleFieldに実装されたexternal関数の引数は全て変えていないので，フロントからそのまま叩けるはず．
  - ただ，battleIdの指定にmsg.senderを使っているので，callerを間違えると欲しいデータが取れない．
  - **大事** : anvilにデプロイしようとするとcontract size limit に引っかかるので，またサイズの削減が必要．
    - これはManagerを直接呼べばいい関数に関してはManagerに実装し直すことで対応できると思っている．（ただしフロントと協力する必要あり）

なお，マッチメイクの部分は，今の実装のままで，
- １人が同時に２つのバトルを提案，申込できない
が達成されていたので，変更していない（MatchStateで排他制御されてる．） 
 
- test/IntegrationMultiSlot.t.sol (ADD)
  -  testMakeProposalByTwo : 二人同時にバトルを提案し，申込みが入る時の排他制御ができているか，  
  - testMultiSlotBattle: ２つのバトルを同時にスタートさせ，battleId:1のラウンド１ =>battleId:２のラウンド１という風に交互にラウンドを走らせてちゃんと最後までバトルが進むか．（１つ１つのアクションレベルでmultithreadなテストは探索範囲が広すぎて書けないので，これはプレイしてtestする必要あり．）

- PLMMatchOrganizer.t.sol (FIX)
  - testProperBattleFlow: try catchでエラーが出ているのにpassしてしまっていたところ，最後assertしていたbattleStateの値をSettledではなくCanceledにしている部分があったことで，がばがばなテストになってたので，直しました．
  - これまでこのガバガバテストでチェックしてしまっていたdevelopブランチは，実行してみて，emitされたeventを見て，正しく動いていることは確認済みです．

# Context

現在，バトルをプレイできる数が１組（２人，１バトル分）になっている．
これはバトル情報を格納・処理するBattleFieldコントラクトの仕様である．
実装方法を変更することで，複数組が同時にバトル可能な仕様にする．
同時に，SSTORE2を使用してstorageの読み書きが多いバトル周りのcallのガス代を削減する．

# TODO
- BattleFIeldのコントラクトサイズリミットを削減
- コメント書く

# Checklist

- [ ] I opened a draft PR or added the `[WIP]` level if my PR is not ready for review.
- [ ] I have reviewed the code by myself.
- [ ] I have assigned an appropriate reviewer for the PR.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests enough to show how your code behaves and that your code works as expected.

# Additional Notes

TODO: Describe any other information you'd like to mention.

2023-02-27 10:22 UTC, terapoon requested changes
@shiinokinoki 
お疲れ様です。コードの可読性が高く、コメントももう少しつけたみはあるものの最低限はついていて良きです。

内容に関しては時間があるときにもう少しちゃんとみたいので、あとでもう一度再レビューするのですが、ひとまず表記等に関していくつかあるので、コードにもコメントをいくつかつけましたが、さっとまとめます。

- コントラクトサイズの上限に問題がなければ、基本的に変数名の過度な省略は避けたい。
    - (e.g.) rr: roundResult, br: battleResult, cc: choiceCommit など
    - 略するにしても統一感が欲しい。cc, cCommit など同じものを指しているが省略の度合いが違うものが散見されたのでそこを統一してほしい。
    - [相談 (好みもあるので)] storage -> stor, strg とかにした方が storage かんあるなあとか思ったりした。(stor, store とかっぽい?)

- 関数の命名に関して
　- putHoge は setHoge の方が良さそう。(put がこの手のもので使われているのをあまりみたことがない。)
　- storeHoge, loadHoge も set, get の方が良い？でも checkpoint は write を使っていたので、write は良さそう。あまり同じような操作を指す動詞を増やしたくないので、set/write, get/read or load くらいの 2 つずつくらいに統一したい。
　
- リファクタ系
　- 気づいた箇所のいくつかにコメントをつけたが、stor.getHoge で同じものを引っ張って使っている場所があったが、ここは memory で一回目を変数で受けて、2回目はそれを使った方がガス代もプログラムのサイズ的にも節約できる気がする。(function call は重い)
　- 今一度全体を見直して上記のような箇所を潰せるだけ潰しておきたい。(あとでやるのは面倒なので)
　
以上です !! ロジックの正しさみたいなところはまだ見切れていないので、もう少しお待ちください。ひとまず作業を止めると悪いので、上記を Request changes として投げます !!

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleField.sol
> +import "forge-std/Test.sol";
これはデバック用？
そうなら消しておきたい。

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleField.sol
> +            (MAX_ROUNDS - manager.getNumRounds(battleId[msg.sender]))
ここ、getNumRounds 2回呼ぶのは勿体無いので、一時変数を使いたいです。

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleField.sol
> +            (MAX_ROUNDS - manager.getNumRounds(battleId[msg.sender]))
同じ関数の中で同じものを 2 回以上呼ぶ時は一時変数で受けることを考えたいです。

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleField.sol
> +    /// FIXME: バトル中のプレイヤーがこの関数を叩けないようにする必要がある．現在onlyMOのrequireでMOからしか叩けないようにして，MOでこの関数を呼ぶ際に排他制御しているが，それで正しいのか．
これで正しいと思います。

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleManager.sol
> +        IPLMBattleField.RoundResult calldata rr
変数名 rr -> roundResult とかにしたい

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleManager.sol
> +        IPLMBattleField.BattleResult calldata br
こちらも br はやめたい

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleManager.sol
> +        IPLMBattleField.ChoiceCommit memory cc = _getChoiceCommit(
cc とかの変数は避けたいな...
これってコントラクトサイズの都合なのか？

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleManager.sol
> +        IPLMBattleField.PlayerSeedCommit memory psc = _getPlayerSeedCommit(
psc

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleManager.sol
> +        IPLMBattleField.PlayerInfo memory pI = _getPlayerInfo(
pI

2023-02-27 10:22 UTC, terapoon commented on src/PLMBattleStorage.sol
> +    function storeNumRounds(uint256 battleId, uint256 numRounds) external {
関数の命名に関して
store, put, などがあるが、基本 set で 直接書き込んでいて違う表現を使っている部分で write とかに統一したほうがいいかも。
ちょっと統一感がなさみ。

2023-03-04 04:58 UTC, shiinokinoki commented
>リファクタ系
　- 気づいた箇所のいくつかにコメントをつけたが、stor.getHoge で同じものを引っ張って使っている場所があったが、ここは memory で一回目を変数で受けて、2回目はそれを使った方がガス代もプログラムのサイズ的にも節約できる気がする。(function call は重い)
　- 今一度全体を見直して上記のような箇所を潰せるだけ潰しておきたい。(あとでやるのは面倒なので)

PLMBattleField全体でこれがなくなるように修正入れました．

2023-03-07 07:29 UTC, terapoon requested changes
頑張ってください...!!

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        _status[msg.sender] = _NOT_ENTERED;
これで防げているのは、同じアカウントによる nonReentrant がついている関数の同時コール

Q. 同じバトルに入っている二人のユーザー (Alice, Bob) が同時に nonReentrant がついている関数を呼べるが、これって大丈夫だっけ？
(レビューしながら考えます。思いついたら後でかく)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +    modifier nonReentrant() {
オリジナルの nonReentrant と名前は変えたほうがいいかも (オリジナルを知っている人は勘違いする可能性がある?)

いい感じにオリジナルネームをつけたい。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +    modifier nonReentrant() {
そんなにコントラクトサイズ変わらないかもやけど、ここはインライン展開してしまってもいい気がした。(任せます。)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +    uint256 private constant _NOT_ENTERED = 1;
Q. これって、uint256 にしないとまずいんだっけ？ (bool だと問題がある？)
オリジナルの nonReentrant が uint256 だった気もするので何か訳があって uint256 にしている可能性もあるか (?)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +    mapping(address => uint256) private _status;
address => bool ではダメなんでしたっけ？
コントラクトサイズは減りそうなので慎重に検討したい。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        {
この謎の括弧いらない気がします。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +    function setPlayerInfoWinCount(
一気に二つ以上加算する場合がないなら、引数を一つ減らして incrementPlayerInfoWinCount とかでいいかも。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            if (homeDamage > visitorDamage) {
あんま意味ないかもやけど (コントラクトサイズが変わらないならやる意味ないかも)
ここの 勝ち負け引き分けの判定後のロジックがほぼ同じやから補助関数を作ると記述量が減って多少コントラクトサイズが減るかもとか思った

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            if (homeDamage > visitorDamage) {
勝者、敗者、引き分けかどうかのフラグ、照射のダメージ、敗者のダメージが引数か

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            if (homeDamage > visitorDamage) {
10 行は減りそうなのでやってもいいかも

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +    function setNumRounds(uint256 _battleId, uint8 numRound)
これも (setPlayerInfoWinCount の方を先にコメントした都合でこれもになっている)
基本単調増加で一ずつしか増えないなら incrementNumRounds でいい気がする。引数が減るというメリットあり。BF 側のサイズも若干やけど減りそう

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        numRounds = manager.getNumRounds(battleId[msg.sender]);
ここは getter を使ってとってこなくても値は確定しているように見える (?)
関数コールが一回減らせるかも

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        numRounds = manager.getNumRounds(battleId[msg.sender]);
一行上の setNumRounds の引数に与えた numRounds + 1 が返ってくるはずなのでただのインクリメントでいい気がする。

このコントラクトで numRounds を保存しないなら変数を書き換えるのはコストがかかるのでこの下で出てくるところをすべて numRounds の代わりに numRounds + 1 とすれば良いだけか (?)
ただ可読性は落ちそうなので要検討

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        numRounds = manager.getNumRounds(battleId[msg.sender]);
numRounds は 215 行目で getter からとってきてるので、少なくともここの getter はいらなそう。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        _status[msg.sender] = _NOT_ENTERED;
やっぱりまずい気がする。
Alice が commit 済みで Bob が commit するのと Alice が reveal するのが同時に起こると、攻撃があり得そうな気がしているので今考え中。

Q. なんかこれまずいケースがあったから nonReentrant つけた気がしてるんやけど、覚えてますか...??

ちなみに、これも防ごうとするなら、battleId ごとに _ENTERED, _NOT_ENTERED を持たせる実装に変えれば良い。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            manager.getPlayerInfo(battleId[msg.sender], PlayerId.Home).addr,
setter は setPlayerInfoHoge ってなっているが、getter は全体で取ってきてメンバアクセスしているが、ガス代の観点から言うと、これはオリジナルのコントラクト側 (manager 側) でメンバアクセスしたものをリターンするのがベストプラクティスだったように思うので、やったほうがいいかも。

BF 側で受け取るものが構造体になっていることからも、BF のコントラクトサイズにも多少影響している可能性がありそう。

多分この実装だと、BF 側のプログラムが、構造体を一度格納して、その一部をとるみたいな感じになっているはずで、その部分の実装が BF コントラクトに来ていると推測できるため、manager 側に押し遣ることで BF のコントラクトサイズは小さくなるのではないかと考えています。

ここ以外にも getPlayerInfo(...).huga みたいなのはすべて直接 getPlayerInfoHuga にしたほうがいいかな

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            manager.getPlayerInfo(battleId[msg.sender], PlayerId.Home).addr,
getPlayerInfo 系をすべて対処したら結構コントラクトサイズ減るんじゃないかな...??

(減らんかったらすいません...)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +            .getChoiceCommit(battleId[msg.sender], numRounds, playerId)
ここも getChoiceCommit で commit の構造体を BF 側に全部ロードするとその分のプログラムがコンパイルの結果生成されるので、 Choice enum を直接 fetch してくるようにしたらコントラクトサイズが減るんじゃないかと思っている。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        ChoiceCommit memory choiceCommit = manager.getChoiceCommit(
terapoon が書いたコードなんですが、
これよくよく考えたら ChoiceCommit 全体取ってくる必要なくて、commitString だけで十分ですね。

ここも追加の getter を manager に追加して commitString だけ取ってくるようにしたほうがいい

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        manager.setPlayerInfoRemainingLevelPoint(
操作内容が set ではなくて subtract だと思うので、ここの関数名は変えたほうが良さそう。
levelPoint を set したんかなって思ってしまいそう。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        manager.setPlayerInfoRemainingLevelPoint(
BF 側で引き算をしてその値を set する実装ならこのままの間数名で良さそう

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        manager.setPlayerInfoRemainingLevelPoint(
まあでも引き算は manager に押しやった方が BF は軽くなるか

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +        _status[msg.sender] = _NOT_ENTERED;
同じストレージ領域を読み書きしているけど、その順番が確定できるならこのままでよくて、まずい順番で読み書きされる可能性が存在するならダメやな。

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleField.sol
> +    ) external onlyMatchOrganizer {
readyForBattleStart で確認していたものは MO で制御しているのか? (後で見る)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +     * @dev See {IERC721Enumerable-battleOfPlayerByIndex}.
このコメントはなんだ？

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +     * @dev See {ERC721-_beforeBattleTransfer}.
このコメントはなんだ？

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +    // TODO: BattleFieldからしか呼べないようにするrequireが必要．出ないと，誰でもバトル結果を書き換えられてしまう．
この TODO は解決済み？

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +        nonReentrant
この nonReentrat は呼び出し元の requestChallenge 関数が nonReentrant だからいらないはず

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +contract PLMBattleManager is ReentrancyGuard {
ReentrancyGuard いらないと思う。
(基本的にこう言う排他制御は一番トップの呼び出し元で行うし、このコントラクトは直接呼ばれることはないのでいらない。使用箇所にもコメントをしたのでそちらも参照。)

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleManager.sol
> +        nonReentrant
これ、onlyBF (?) しないと不味くない？

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleStorage.sol
> +    /// @notice store numRounds by SSTORE2. It is read only, so overwrite all data when updating.
writer 系、これだと誰でも呼べるのでまずそう？

2023-03-07 07:29 UTC, terapoon commented on src/PLMBattleStorage.sol
> +    function loadNumRounds(uint256 battleId) external view returns (uint8) {
loader 系は誰から読み出されてもいいので、このままで良さそう (just a comment)

2023-03-08 07:37 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +        _status[msg.sender] = _NOT_ENTERED;
battleID to status のmapping でreentrancy guard のstatusを管理するように変更しました．

2023-03-08 07:39 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +        {
必要な理由のコメントつけました．

2023-03-08 12:53 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +            manager.getPlayerInfo(battleId[msg.sender], PlayerId.Home).addr,
![image](https://user-images.githubusercontent.com/49639555/223718235-6a54a1be-f88e-4dd4-adec-75ae4bc40221.png)

2023-03-08 12:53 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +            manager.getPlayerInfo(battleId[msg.sender], PlayerId.Home).addr,
![image](https://user-images.githubusercontent.com/49639555/223718301-c482e999-a0d3-487d-b034-60424ef291b4.png)

2023-03-09 08:16 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +    uint256 private constant _NOT_ENTERED = 1;
オリジナルがuint256にしているので，そのままにしておきます

2023-03-09 09:13 UTC, shiinokinoki commented
@terapoon 
上記でいただいたレビューは反映しました．
追加でコントラクトサイズ削減のため，
- playerIdを廃止して全てaddressで管理（引数を減らす）
- 各種getterを削除
- その他 managerに記載可能な処理を移行
を実施し，unittestは全てpass, また，全てサイズが収まり，anvilにdeploy成功しました．

2023-03-10 01:23 UTC, shiinokinoki commented
残りのタスク
- このブランチの変更に合わせたfrontendの修正（はっしーさんと協力）
- 特性実装
- エラービットマップ（nice to have）
- anvilでデバッグ（これは椎木がやっちゃったほうが早いかも）
- testnetデバッグ（これも）
- github README反映

2023-03-10 04:13 UTC, terapoon commented on src/PLMBattleField.sol
> +    uint256 private constant _NOT_ENTERED = 1;
承知、オリジナルの実装では uint256 なので bool ではなくオリジナルの方式を踏襲している旨を軽くコードにコメント書いておいてもらえるとです !!

2023-03-10 04:14 UTC, terapoon commented on src/PLMBattleField.sol
> +    ) external onlyMatchOrganizer {
@shiinokinoki マルチスロットだから、バトルの状態の確認とかがいらないから、readyForBattleStart に当たる確認操作は不要になったんでした。

コメント確認して、おかしいことを言っていなければ resolve conversation お願いします。

2023-03-10 04:16 UTC, terapoon commented
@shiinokinoki お疲れ様。
コントラクトサイズ削減周りを今からレビューします。
残タスクは、小分けにして issue を立ててもらえると嬉しいです。
あと、今立っている issue でもう終わっているのを閉じたり、まだ対応できていない部分を改めて確認する作業をお願いしたい !!

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +    mapping(uint256 => uint256) private _status;
コメントで battleId => locked flag 的なのが欲しいです。
what to what の mapping なのか

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +            _status[battleId[msg.sender]] != _ENTERED,
めっちゃ細かいけど、
map1[map2[key]]
って、
tmp = map2[key]
map1[tmp]
にコンパイルされるはずだから、tmp を2回使うなら一度変数受けしてそれを使い回す方がプログラムサイズは小さくなるはず。

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +        _markSlot(enemyAddr[msg.sender]);
ここも、enemyAddr[msg.sender] を複数回参照しているから一度変数で受ける方が良いかも

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +
めっちゃ簡潔になった ! great !
(お気持ちなので resolve しちゃってください)

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +                : enemyAddr[msg.sender];
同じ mapping の同じ entry へのアクセス重複が多めなのが気になるところ。(上のところでも言及した通り、一時変数受けするのがベター)

→ solidity のコンパイラはとても優秀とは言えない(はずな)ので、柔軟な対処ができないと思っていて、一時変数受けの工夫をすると差が出ると思っている。

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
>          // TODO: modify here when we implement multislot battle.
Resolve された TODO だと思うので、消しておいてください

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +        return manager.getPlayerInfoRandomSlot(msg.sender).nonce;
ここも getter バラせたりする？

2023-03-10 04:38 UTC, terapoon commented on src/PLMBattleField.sol
> +        emit PlayerSeedCommitted(battleId[msg.sender], msg.sender);
battleId[msg.sender] を何回も使っているので変数受けしたい

2023-03-11 02:41 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +
ありがとうございます！

2023-03-11 04:46 UTC, shiinokinoki commented
#152 対応済み

2023-03-11 05:39 UTC, shiinokinoki commented on src/PLMBattleField.sol
> +    ) external onlyMatchOrganizer {
問題ないと思います

2023-03-11 08:16 UTC, terapoon approved these changes
お疲れ様 !
コミットまとめたら merge して大丈夫です。

その後、develop -> main の merge も流れでやっちゃいましょう !!

2023-03-11 17:23 UTC, merged